name: Update Version File

# CINTENT >> MANUAL TRIGGER
# on:
#   pull_request:
#     paths:
#       - "pyproject.toml"
#     branches:
#       - master
on: [repository_dispatch, workflow_dispatch]

jobs:
  update-version:
    runs-on: ubuntu-latest

    # CINTENT >> REMOVE_TRIGGER
    # Don't run on fork PRs
    # if: github.event.pull_request.head.repo.full_name == github.repository

    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          
      # CINTENT >> INSERT_CINTENT
      - uses: JavidDitty/setup-cintent@3638849e94bdb037f0a405375686a8550e6df904
        with:
          nonblocking: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Update comfyui_version.py
        run: |
          # Read version from pyproject.toml and update comfyui_version.py
          python -c '
          import tomllib

          # Read version from pyproject.toml
          with open("pyproject.toml", "rb") as f:
              config = tomllib.load(f)
              version = config["project"]["version"]

          # Write version to comfyui_version.py
          with open("comfyui_version.py", "w") as f:
              f.write("# This file is automatically generated by the build process when version is\n")
              f.write("# updated in pyproject.toml.\n")
              f.write(f"__version__ = \"{version}\"\n")
          '

      # CINTENT >> REMOVE_UPLOADS
      # - name: Commit changes
      #   run: |
      #     git config --local user.name "github-actions"
      #     git config --local user.email "github-actions@github.com"
      #     git fetch origin ${{ github.head_ref }}
      #     git checkout -B ${{ github.head_ref }} origin/${{ github.head_ref }}
      #     git add comfyui_version.py
      #     git diff --quiet && git diff --staged --quiet || git commit -m "chore: Update comfyui_version.py to match pyproject.toml"
      #     git push origin HEAD:${{ github.head_ref }}

      # CINTENT >> INSERT_CINTENT
      - name: Upload CIntent Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ env.CINTENT_ARTIFACT_NAME }}
          path: ${{ env.CINTENT_LOGS }}
